version: '3.8'

services:
  auth-ui:
    build: .
    container_name: auth-ui
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      # <-- Backend ile aynı ağa bağlanıyor
      - auth_network
    # Windows kullanıyorsan dosya değişimini algılaması için:
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  auth_network:
    external: true
